CREATE TABLE media (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    title VARCHAR(255) NOT NULL,
    original_title VARCHAR(255),
    description TEXT,

    type VARCHAR(20) NOT NULL,
    release_date DATE,

    poster_url VARCHAR(2048),
    backdrop_url VARCHAR(2048),

    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,

    CONSTRAINT chk_media_type
        CHECK (type IN ('MOVIE', 'SERIES', 'BOOK'))
);

CREATE INDEX idx_media_type ON media (type);
